// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYn3QWmbmtFnsCfZQDoak9pyw7Y8l6c4U',
    appId: '1:307770461989:web:70c980968b14a5dca394cc',
    messagingSenderId: '307770461989',
    projectId: 'nutriticket-app',
    authDomain: 'nutriticket-app.firebaseapp.com',
    storageBucket: 'nutriticket-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdAB5Db2Ay82woyG4HH5_npMcr4D1p_E',
    appId: '1:307770461989:android:59de900f32dba4c9a394cc',
    messagingSenderId: '307770461989',
    projectId: 'nutriticket-app',
    storageBucket: 'nutriticket-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWpJnEyI4YyLnRsAHURyxDZgWPgifzpQ',
    appId: '1:307770461989:ios:829f1571f176b02ca394cc',
    messagingSenderId: '307770461989',
    projectId: 'nutriticket-app',
    storageBucket: 'nutriticket-app.firebasestorage.app',
    iosBundleId: 'com.example.nutriticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWpJnEyI4YyLnRsAHURyxDZgWPgifzpQ',
    appId: '1:307770461989:ios:829f1571f176b02ca394cc',
    messagingSenderId: '307770461989',
    projectId: 'nutriticket-app',
    storageBucket: 'nutriticket-app.firebasestorage.app',
    iosBundleId: 'com.example.nutriticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYn3QWmbmtFnsCfZQDoak9pyw7Y8l6c4U',
    appId: '1:307770461989:web:5b49d9ceca9f7388a394cc',
    messagingSenderId: '307770461989',
    projectId: 'nutriticket-app',
    authDomain: 'nutriticket-app.firebaseapp.com',
    storageBucket: 'nutriticket-app.firebasestorage.app',
  );
}
